/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Modelo.Actores;
import Modelo.ActoresDAO;
import Modelo.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author almudenaflores
 */
public class JFActores extends javax.swing.JFrame {

    /** Creates new form Actores */
    public JFActores() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        txtNombre = new java.awt.TextField();
        txtApellidos = new java.awt.TextField();
        txtAño = new java.awt.TextField();
        txtNacionalidad = new java.awt.TextField();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        btnGuardar = new java.awt.Button();
        btnModificar = new java.awt.Button();
        btnAsociar = new java.awt.Button();
        btnListar = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btnAtras = new javax.swing.JButton();
        label6 = new java.awt.Label();
        txtId = new java.awt.TextField();
        btnEliminar = new java.awt.Button();
        btnBuscar = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actores");
        setBackground(new java.awt.Color(216, 233, 235));
        setMinimumSize(new java.awt.Dimension(530, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        label1.setText("ACTORES");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 120, 65));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 120, -1));
        getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 120, -1));
        getContentPane().add(txtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 120, -1));
        getContentPane().add(txtNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 120, -1));

        label2.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        label2.setText("Nombre");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        label3.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        label3.setText("Apellidos");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        label4.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        label4.setText("Año de nacimiento");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        label5.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        label5.setText("Nacionalidad");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        btnGuardar.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        btnGuardar.setLabel("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 100, -1));

        btnModificar.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        btnModificar.setLabel("Modificar");
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 100, -1));

        btnAsociar.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        btnAsociar.setLabel("Asociar");
        getContentPane().add(btnAsociar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 100, -1));

        btnListar.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        btnListar.setLabel("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        getContentPane().add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 100, -1));

        jTable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 204, 255)));
        jTable.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellidos", "Año nacimiento", "Nacionalidad"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 500, 170));

        btnAtras.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, -1, -1));

        label6.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        label6.setText("ID");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 120, -1));

        btnEliminar.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        btnEliminar.setLabel("Eliminar");
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 100, -1));

        btnBuscar.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        btnBuscar.setLabel("Buscar");
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
       ArrayList listaActores=new ArrayList();
        Actores actores;
        
        try {
            Connection bd=Conexion.getConexion();
            PreparedStatement ps= bd.prepareStatement("SELECT * FROM Actores");
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                actores=new Actores();
                actores.setNombre(rs.getString(1));
                actores.setApellidos(rs.getString(2));
                actores.setNacionalidad(rs.getString(3));
                actores.setAnio(rs.getInt(4));
                listaActores.add(actores);
                
            }
            
        } catch (Exception e) {
            System.out.println("error");
        }
        
        //return listaActores;
        /**ActoresDAO actoresDAO=new ActoresDAO(); 
        
        DefaultTableModel modeloT=new DefaultTableModel();
        //tablaD.setModel(modeloT);
        
        modeloT.addColumn("Nombre");
        modeloT.addColumn("Apellidos");
        modeloT.addColumn("Año de nacimiento");
        modeloT.addColumn("Nacionalidad");
        
        Object[] columna =new Object[4];
        int numRegistros=actoresDAO.listActores().size();
        
        for(int i=0; i<numRegistros; i++){
            columna[0]=actoresDAO.listActores().get(i).getNombre();
            columna[1]=actoresDAO.listActores().get(i).getApellidos();
            columna[2]=actoresDAO.listActores().get(i).getAnio();
            columna[3]=actoresDAO.listActores().get(i).getNacionalidad();
            modeloT.addRow(columna);
        }*/
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFActores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFActores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFActores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFActores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFActores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public java.awt.Button btnAsociar;
    public javax.swing.JButton btnAtras;
    public java.awt.Button btnBuscar;
    public java.awt.Button btnEliminar;
    public java.awt.Button btnGuardar;
    public java.awt.Button btnListar;
    public java.awt.Button btnModificar;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable;
    public java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    public java.awt.Label label6;
    public java.awt.TextField txtApellidos;
    public java.awt.TextField txtAño;
    public java.awt.TextField txtId;
    public java.awt.TextField txtNacionalidad;
    public java.awt.TextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
