/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author almudenaflores
 */
public class JFPeliculas extends javax.swing.JFrame {

    /**
     * Creates new form Peliculas
     */
    public JFPeliculas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        txtTitulo = new java.awt.TextField();
        txtAño = new java.awt.TextField();
        txtDuracion = new java.awt.TextField();
        txtResumen = new java.awt.TextField();
        btnGuardar = new java.awt.Button();
        btnModificar = new java.awt.Button();
        btnAsociar = new java.awt.Button();
        btnListar = new java.awt.Button();
        btnAtras = new java.awt.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        label6 = new java.awt.Label();
        txtID = new java.awt.TextField();
        btnEliminar = new java.awt.Button();
        btnBuscar = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(530, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        label1.setText("PELÍCULAS");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 140, 50));

        label2.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        label2.setText("Título");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        label3.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        label3.setText("Año");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        label4.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        label4.setText("Duración");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        label5.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        label5.setText("Resumen");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 130, -1));

        txtAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAñoActionPerformed(evt);
            }
        });
        getContentPane().add(txtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 50, -1));
        getContentPane().add(txtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 50, -1));

        txtResumen.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        txtResumen.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txtResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 140, 50));

        btnGuardar.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        btnGuardar.setLabel("Guardar");
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 100, -1));

        btnModificar.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        btnModificar.setLabel("Modificar");
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 100, -1));

        btnAsociar.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        btnAsociar.setLabel("Asociar");
        getContentPane().add(btnAsociar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 100, -1));

        btnListar.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        btnListar.setLabel("Listar");
        getContentPane().add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 100, -1));

        btnAtras.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        btnAtras.setLabel("Atrás");
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 80, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 470, 140));

        label6.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        label6.setText("ID");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtID.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 50, -1));

        btnEliminar.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        btnEliminar.setLabel("Eliminar");
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 100, 30));

        btnBuscar.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        btnBuscar.setLabel("Buscar");
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAñoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPeliculas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public java.awt.Button btnAsociar;
    public java.awt.Button btnAtras;
    public java.awt.Button btnBuscar;
    public java.awt.Button btnEliminar;
    public java.awt.Button btnGuardar;
    public java.awt.Button btnListar;
    public java.awt.Button btnModificar;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    public java.awt.TextField txtAño;
    public java.awt.TextField txtDuracion;
    public java.awt.TextField txtID;
    public java.awt.TextField txtResumen;
    public java.awt.TextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
